name: Web3ExplorerWs CD
on:
    push:
        branches:
          main
env:
    node-version: 20.11.1

jobs:
  release:
    name: Release pushed tag
    runs-on: windows-latest
    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: npm
        run: |
          npm install
          cd node_modules/secp256k1
          dir build/Release

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v1" --repo="${{ github.repository }}" --title="v1" --draft --generate-notes
          echo "Release created."
          gh release upload v1 node_modules/secp256k1/build/Release/secp256k1.a

